#!/bin/bash
# colors
gray='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
violet='\033[1;34m'
magenta='\033[1;35m'
blue='\033[1;36m'
white='\033[1;37m'
reset='\033[0m'

echo -en ${white}"Остановка jNode... PID:${red}$(pidof java)\n\n"${reset}
bash ~/jnode/bin/run.sh stop
if [ "$(pidof java)" = "" ]
then
echo -en ${yellow}"jNode не запущена.\n"${reset};
fi
echo
read -sp "Нажмите Enter для завершения"
echo
echo "Ок"
exit
