#!/bin/bash

##################################
#        jNode stop script       #
#    only for Termux / Android   #
# Copyright (c) 2023 by 2:50/700 #
##################################

# colors
gray='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
violet='\033[1;34m'
magenta='\033[1;35m'
blue='\033[1;36m'
white='\033[1;37m'
reset='\033[0m'

echo -en ${white}"\nОстановка jNode... PID:${red}$(pidof java)\n\n"${reset}
bash ~/jnode/bin/ru.sh stop
echo
read -sp "Нажмите Enter для завершения"
echo -en "\nОк\n\n"
exit
