#!/bin/bash

##################################
#    jNode check status script   #
#    only for Termux / Android   #
# Copyright (c) 2023 by 2:50/700 #
##################################

JPID=$(pidof java)
gray='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
violet='\033[1;34m'
magenta='\033[1;35m'
blue='\033[1;36m'
white='\033[1;37m'
reset='\033[0m'

echo -en ${white}"\nПроверка состояния jNode...\n"${reset}

if [ "$JPID" = "" ]
then
echo -en "\n\njNode ${yellow}НЕ${reset} запущена.\n\n";
else
echo -en "\n\n${yellow}jNode запущена!\n\nPID:${red}$JPID\n\n"${reset}
fi
echo
read -sp "Нажмите Enter для выхода"
echo -en "\n\nOk\n\n"
exit
